modLoader="javafml"
loaderVersion="[36,)"
license="Academic Free License v3.0"

[[mods]]
modId="shamanking"
version="1.0.0"
displayName="Shaman King"
credits="Made by Shin"
displayURL="https://mcreator.net"
authors="Shin"
description='''
Based on the anime and manga 'Shaman King'
'''

[[dependencies.shamanking]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




